server:
  port: 8091

springfox:
  title: '@title@'
  version: '@version@'

fint:
  adapter:
    endpoints:
      sse: /sse/%s
      status: /status
      response: /response

  oauth:
    enabled: true
    access-token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
    scope: fint-client

  internal-files:
    directory: file-cache

security:
  basic:
    enabled: false

