
package no.geointegrasjon.arkiv.oppdatering;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.5
 * 2024-12-18T13:51:15.066+01:00
 * Generated source version: 3.5.5
 */

@WebFault(name = "ApplicationFault", targetNamespace = "http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")
public class ApplicationException extends Exception {

    private no.geointegrasjon.arkiv.oppdatering.ApplicationFault faultInfo;

    public ApplicationException() {
        super();
    }

    public ApplicationException(String message) {
        super(message);
    }

    public ApplicationException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ApplicationException(String message, no.geointegrasjon.arkiv.oppdatering.ApplicationFault applicationFault) {
        super(message);
        this.faultInfo = applicationFault;
    }

    public ApplicationException(String message, no.geointegrasjon.arkiv.oppdatering.ApplicationFault applicationFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = applicationFault;
    }

    public no.geointegrasjon.arkiv.oppdatering.ApplicationFault getFaultInfo() {
        return this.faultInfo;
    }
}
