
package no.geointegrasjon.arkiv.oppdatering;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.5
 * 2024-12-18T13:51:15.052+01:00
 * Generated source version: 3.5.5
 */

@WebFault(name = "FinderFault", targetNamespace = "http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")
public class FinderException extends Exception {

    private no.geointegrasjon.arkiv.oppdatering.FinderFault faultInfo;

    public FinderException() {
        super();
    }

    public FinderException(String message) {
        super(message);
    }

    public FinderException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public FinderException(String message, no.geointegrasjon.arkiv.oppdatering.FinderFault finderFault) {
        super(message);
        this.faultInfo = finderFault;
    }

    public FinderException(String message, no.geointegrasjon.arkiv.oppdatering.FinderFault finderFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = finderFault;
    }

    public no.geointegrasjon.arkiv.oppdatering.FinderFault getFaultInfo() {
        return this.faultInfo;
    }
}
