
package no.geointegrasjon.arkiv.oppdatering;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.5
 * 2024-12-18T13:51:15.063+01:00
 * Generated source version: 3.5.5
 */

@WebFault(name = "OperationalFault", targetNamespace = "http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")
public class OperationalException extends Exception {

    private no.geointegrasjon.arkiv.oppdatering.OperationalFault faultInfo;

    public OperationalException() {
        super();
    }

    public OperationalException(String message) {
        super(message);
    }

    public OperationalException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public OperationalException(String message, no.geointegrasjon.arkiv.oppdatering.OperationalFault operationalFault) {
        super(message);
        this.faultInfo = operationalFault;
    }

    public OperationalException(String message, no.geointegrasjon.arkiv.oppdatering.OperationalFault operationalFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = operationalFault;
    }

    public no.geointegrasjon.arkiv.oppdatering.OperationalFault getFaultInfo() {
        return this.faultInfo;
    }
}
