package no.geointegrasjon.arkiv.oppdatering;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2024-12-18T13:51:15.081+01:00
 * Generated source version: 3.5.5
 *
 */
@WebServiceClient(name = "OppdateringService",
                  wsdlLocation = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/giArkivOppdatering20120131.wsdl",
                  targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
public class OppdateringService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", "OppdateringService");
    public final static QName SakArkivOppdatering = new QName("http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", "SakArkivOppdatering");
    static {
        WSDL_LOCATION = OppdateringService.class.getResource("wsdl/giArkivOppdatering20120131.wsdl");
    }

    public OppdateringService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OppdateringService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OppdateringService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OppdateringService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OppdateringService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OppdateringService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SakArkivOppdateringPort
     */
    @WebEndpoint(name = "SakArkivOppdatering")
    public SakArkivOppdateringPort getSakArkivOppdatering() {
        return super.getPort(SakArkivOppdatering, SakArkivOppdateringPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SakArkivOppdateringPort
     */
    @WebEndpoint(name = "SakArkivOppdatering")
    public SakArkivOppdateringPort getSakArkivOppdatering(WebServiceFeature... features) {
        return super.getPort(SakArkivOppdatering, SakArkivOppdateringPort.class, features);
    }

}
