
package no.geointegrasjon.arkiv.oppdatering;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2024-12-18T13:51:14.997+01:00
 * Generated source version: 3.5.5
 *
 */
public final class SakArkivOppdateringPort_SakArkivOppdatering_Client {

    private static final QName SERVICE_NAME = new QName("http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", "OppdateringService");

    private SakArkivOppdateringPort_SakArkivOppdatering_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OppdateringService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        OppdateringService ss = new OppdateringService(wsdlURL, SERVICE_NAME);
        SakArkivOppdateringPort port = ss.getSakArkivOppdatering();

        {
        System.out.println("Invoking finnJournalpostRestanser...");
        no.geointegrasjon.arkiv.oppdatering.Ansvarlig _finnJournalpostRestanser_ansvarlig = null;
        java.lang.Boolean _finnJournalpostRestanser_returnerMerknad = null;
        java.lang.Boolean _finnJournalpostRestanser_returnerTilleggsinformasjon = null;
        java.lang.Boolean _finnJournalpostRestanser_returnerKorrespondansepart = null;
        java.lang.Boolean _finnJournalpostRestanser_returnerAvskrivning = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _finnJournalpostRestanser_kontekst = null;
        try {
            no.geointegrasjon.arkiv.oppdatering.JournalpostListe _finnJournalpostRestanser__return = port.finnJournalpostRestanser(_finnJournalpostRestanser_ansvarlig, _finnJournalpostRestanser_returnerMerknad, _finnJournalpostRestanser_returnerTilleggsinformasjon, _finnJournalpostRestanser_returnerKorrespondansepart, _finnJournalpostRestanser_returnerAvskrivning, _finnJournalpostRestanser_kontekst);
            System.out.println("finnJournalpostRestanser.result=" + _finnJournalpostRestanser__return);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking oppdaterMappeStatus...");
        no.geointegrasjon.arkiv.oppdatering.Saksstatus _oppdaterMappeStatus_saksstatuskode = null;
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel _oppdaterMappeStatus_saksnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _oppdaterMappeStatus_kontekst = null;
        try {
            no.geointegrasjon.arkiv.oppdatering.Saksmappe _oppdaterMappeStatus__return = port.oppdaterMappeStatus(_oppdaterMappeStatus_saksstatuskode, _oppdaterMappeStatus_saksnokkel, _oppdaterMappeStatus_kontekst);
            System.out.println("oppdaterMappeStatus.result=" + _oppdaterMappeStatus__return);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking slettBygning...");
        no.geointegrasjon.arkiv.oppdatering.ByggIdentListe _slettBygning_bygninger = null;
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel _slettBygning_saksnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _slettBygning_kontekst = null;
        try {
            port.slettBygning(_slettBygning_bygninger, _slettBygning_saksnokkel, _slettBygning_kontekst);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking nyAvskrivning...");
        no.geointegrasjon.arkiv.oppdatering.AvskrivningListe _nyAvskrivning_avskrivning = null;
        no.geointegrasjon.arkiv.oppdatering.Journpostnoekkel _nyAvskrivning_journalnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _nyAvskrivning_kontekst = null;
        try {
            port.nyAvskrivning(_nyAvskrivning_avskrivning, _nyAvskrivning_journalnokkel, _nyAvskrivning_kontekst);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking oppdaterPlan...");
        no.geointegrasjon.arkiv.oppdatering.NasjonalArealplanId _oppdaterPlan_planid = null;
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel _oppdaterPlan_saksnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _oppdaterPlan_kontekst = null;
        try {
            port.oppdaterPlan(_oppdaterPlan_planid, _oppdaterPlan_saksnokkel, _oppdaterPlan_kontekst);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking nyPunkt...");
        no.geointegrasjon.arkiv.oppdatering.PunktListe _nyPunkt_posisjon = null;
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel _nyPunkt_saksnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _nyPunkt_kontekst = null;
        try {
            port.nyPunkt(_nyPunkt_posisjon, _nyPunkt_saksnokkel, _nyPunkt_kontekst);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking nyJournalpostMerknad...");
        no.geointegrasjon.arkiv.oppdatering.MerknadListe _nyJournalpostMerknad_merknad = null;
        no.geointegrasjon.arkiv.oppdatering.Journpostnoekkel _nyJournalpostMerknad_journalnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _nyJournalpostMerknad_kontekst = null;
        try {
            port.nyJournalpostMerknad(_nyJournalpostMerknad_merknad, _nyJournalpostMerknad_journalnokkel, _nyJournalpostMerknad_kontekst);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking slettJournalpostTilleggsinformasjon...");
        no.geointegrasjon.arkiv.oppdatering.StringListe _slettJournalpostTilleggsinformasjon_systemID = null;
        no.geointegrasjon.arkiv.oppdatering.Journpostnoekkel _slettJournalpostTilleggsinformasjon_journalnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _slettJournalpostTilleggsinformasjon_kontekst = null;
        try {
            port.slettJournalpostTilleggsinformasjon(_slettJournalpostTilleggsinformasjon_systemID, _slettJournalpostTilleggsinformasjon_journalnokkel, _slettJournalpostTilleggsinformasjon_kontekst);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking nySaksmappe...");
        no.geointegrasjon.arkiv.oppdatering.Saksmappe _nySaksmappe_mappe = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _nySaksmappe_kontekst = null;
        try {
            no.geointegrasjon.arkiv.oppdatering.Saksmappe _nySaksmappe__return = port.nySaksmappe(_nySaksmappe_mappe, _nySaksmappe_kontekst);
            System.out.println("nySaksmappe.result=" + _nySaksmappe__return);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking oppdaterJournalpostEksternNoekkel...");
        no.geointegrasjon.arkiv.oppdatering.EksternNoekkel _oppdaterJournalpostEksternNoekkel_nokkel = null;
        no.geointegrasjon.arkiv.oppdatering.Journpostnoekkel _oppdaterJournalpostEksternNoekkel_journalpostnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _oppdaterJournalpostEksternNoekkel_kontekst = null;
        try {
            no.geointegrasjon.arkiv.oppdatering.Journalpost _oppdaterJournalpostEksternNoekkel__return = port.oppdaterJournalpostEksternNoekkel(_oppdaterJournalpostEksternNoekkel_nokkel, _oppdaterJournalpostEksternNoekkel_journalpostnokkel, _oppdaterJournalpostEksternNoekkel_kontekst);
            System.out.println("oppdaterJournalpostEksternNoekkel.result=" + _oppdaterJournalpostEksternNoekkel__return);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking slettMatrikkelnummer...");
        no.geointegrasjon.arkiv.oppdatering.MatrikkelnummerListe _slettMatrikkelnummer_matrikkelnr = null;
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel _slettMatrikkelnummer_saksnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _slettMatrikkelnummer_kontekst = null;
        try {
            port.slettMatrikkelnummer(_slettMatrikkelnummer_matrikkelnr, _slettMatrikkelnummer_saksnokkel, _slettMatrikkelnummer_kontekst);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking nySaksmappeTilleggsinformasjon...");
        no.geointegrasjon.arkiv.oppdatering.TilleggsinformasjonListe _nySaksmappeTilleggsinformasjon_tilleggsinfo = null;
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel _nySaksmappeTilleggsinformasjon_saksnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _nySaksmappeTilleggsinformasjon_kontekst = null;
        try {
            port.nySaksmappeTilleggsinformasjon(_nySaksmappeTilleggsinformasjon_tilleggsinfo, _nySaksmappeTilleggsinformasjon_saksnokkel, _nySaksmappeTilleggsinformasjon_kontekst);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking oppdaterJournalpostStatus...");
        no.geointegrasjon.arkiv.oppdatering.Journalstatus _oppdaterJournalpostStatus_journalstatus = null;
        no.geointegrasjon.arkiv.oppdatering.Journpostnoekkel _oppdaterJournalpostStatus_journalpostnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _oppdaterJournalpostStatus_kontekst = null;
        try {
            port.oppdaterJournalpostStatus(_oppdaterJournalpostStatus_journalstatus, _oppdaterJournalpostStatus_journalpostnokkel, _oppdaterJournalpostStatus_kontekst);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking nySakspart...");
        no.geointegrasjon.arkiv.oppdatering.SakspartListe _nySakspart_sakspart = null;
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel _nySakspart_saksnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _nySakspart_kontekst = null;
        try {
            port.nySakspart(_nySakspart_sakspart, _nySakspart_saksnokkel, _nySakspart_kontekst);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking finnJournalposterUnderArbeid...");
        no.geointegrasjon.arkiv.oppdatering.Ansvarlig _finnJournalposterUnderArbeid_ansvarlig = null;
        java.lang.Boolean _finnJournalposterUnderArbeid_returnerMerknad = null;
        java.lang.Boolean _finnJournalposterUnderArbeid_returnerTilleggsinformasjon = null;
        java.lang.Boolean _finnJournalposterUnderArbeid_returnerKorrespondansepart = null;
        java.lang.Boolean _finnJournalposterUnderArbeid_returnerAvskrivning = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _finnJournalposterUnderArbeid_kontekst = null;
        try {
            no.geointegrasjon.arkiv.oppdatering.JournalpostListe _finnJournalposterUnderArbeid__return = port.finnJournalposterUnderArbeid(_finnJournalposterUnderArbeid_ansvarlig, _finnJournalposterUnderArbeid_returnerMerknad, _finnJournalposterUnderArbeid_returnerTilleggsinformasjon, _finnJournalposterUnderArbeid_returnerKorrespondansepart, _finnJournalposterUnderArbeid_returnerAvskrivning, _finnJournalposterUnderArbeid_kontekst);
            System.out.println("finnJournalposterUnderArbeid.result=" + _finnJournalposterUnderArbeid__return);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking nyMatrikkelnummer...");
        no.geointegrasjon.arkiv.oppdatering.MatrikkelnummerListe _nyMatrikkelnummer_matrikkelnr = null;
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel _nyMatrikkelnummer_saksnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _nyMatrikkelnummer_kontekst = null;
        try {
            port.nyMatrikkelnummer(_nyMatrikkelnummer_matrikkelnr, _nyMatrikkelnummer_saksnokkel, _nyMatrikkelnummer_kontekst);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking nyKorrespondansepart...");
        no.geointegrasjon.arkiv.oppdatering.KorrespondansepartListe _nyKorrespondansepart_part = null;
        no.geointegrasjon.arkiv.oppdatering.Journpostnoekkel _nyKorrespondansepart_journalpostnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _nyKorrespondansepart_kontekst = null;
        try {
            port.nyKorrespondansepart(_nyKorrespondansepart_part, _nyKorrespondansepart_journalpostnokkel, _nyKorrespondansepart_kontekst);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking slettPunkt...");
        no.geointegrasjon.arkiv.oppdatering.PunktListe _slettPunkt_posisjon = null;
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel _slettPunkt_saksnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _slettPunkt_kontekst = null;
        try {
            port.slettPunkt(_slettPunkt_posisjon, _slettPunkt_saksnokkel, _slettPunkt_kontekst);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking nyJournalpost...");
        no.geointegrasjon.arkiv.oppdatering.Journalpost _nyJournalpost_journalpost = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _nyJournalpost_kontekst = null;
        try {
            no.geointegrasjon.arkiv.oppdatering.Journalpost _nyJournalpost__return = port.nyJournalpost(_nyJournalpost_journalpost, _nyJournalpost_kontekst);
            System.out.println("nyJournalpost.result=" + _nyJournalpost__return);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking oppdaterMappeEksternNoekkel...");
        no.geointegrasjon.arkiv.oppdatering.EksternNoekkel _oppdaterMappeEksternNoekkel_nokkel = null;
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel _oppdaterMappeEksternNoekkel_saksnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _oppdaterMappeEksternNoekkel_kontekst = null;
        try {
            no.geointegrasjon.arkiv.oppdatering.Saksmappe _oppdaterMappeEksternNoekkel__return = port.oppdaterMappeEksternNoekkel(_oppdaterMappeEksternNoekkel_nokkel, _oppdaterMappeEksternNoekkel_saksnokkel, _oppdaterMappeEksternNoekkel_kontekst);
            System.out.println("oppdaterMappeEksternNoekkel.result=" + _oppdaterMappeEksternNoekkel__return);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking nySaksmappeMerknad...");
        no.geointegrasjon.arkiv.oppdatering.MerknadListe _nySaksmappeMerknad_merknad = null;
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel _nySaksmappeMerknad_saksnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _nySaksmappeMerknad_kontekst = null;
        try {
            port.nySaksmappeMerknad(_nySaksmappeMerknad_merknad, _nySaksmappeMerknad_saksnokkel, _nySaksmappeMerknad_kontekst);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking oppdaterMappeAnsvarlig...");
        java.lang.String _oppdaterMappeAnsvarlig_nyAdministrativEnhetKode = "";
        java.lang.String _oppdaterMappeAnsvarlig_nySaksbehandlerInit = "";
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel _oppdaterMappeAnsvarlig_saksnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _oppdaterMappeAnsvarlig_kontekst = null;
        try {
            no.geointegrasjon.arkiv.oppdatering.Saksmappe _oppdaterMappeAnsvarlig__return = port.oppdaterMappeAnsvarlig(_oppdaterMappeAnsvarlig_nyAdministrativEnhetKode, _oppdaterMappeAnsvarlig_nySaksbehandlerInit, _oppdaterMappeAnsvarlig_saksnokkel, _oppdaterMappeAnsvarlig_kontekst);
            System.out.println("oppdaterMappeAnsvarlig.result=" + _oppdaterMappeAnsvarlig__return);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking slettSaksmappeTilleggsinformasjon...");
        no.geointegrasjon.arkiv.oppdatering.StringListe _slettSaksmappeTilleggsinformasjon_systemID = null;
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel _slettSaksmappeTilleggsinformasjon_saksnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _slettSaksmappeTilleggsinformasjon_kontekst = null;
        try {
            port.slettSaksmappeTilleggsinformasjon(_slettSaksmappeTilleggsinformasjon_systemID, _slettSaksmappeTilleggsinformasjon_saksnokkel, _slettSaksmappeTilleggsinformasjon_kontekst);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking slettSakspart...");
        no.geointegrasjon.arkiv.oppdatering.StringListe _slettSakspart_systemID = null;
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel _slettSakspart_saksnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _slettSakspart_kontekst = null;
        try {
            port.slettSakspart(_slettSakspart_systemID, _slettSakspart_saksnokkel, _slettSakspart_kontekst);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking slettSaksmappeMerknad...");
        no.geointegrasjon.arkiv.oppdatering.StringListe _slettSaksmappeMerknad_systemID = null;
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel _slettSaksmappeMerknad_saksnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _slettSaksmappeMerknad_kontekst = null;
        try {
            port.slettSaksmappeMerknad(_slettSaksmappeMerknad_systemID, _slettSaksmappeMerknad_saksnokkel, _slettSaksmappeMerknad_kontekst);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking slettAvskrivning...");
        no.geointegrasjon.arkiv.oppdatering.StringListe _slettAvskrivning_systemID = null;
        no.geointegrasjon.arkiv.oppdatering.Journpostnoekkel _slettAvskrivning_journalnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _slettAvskrivning_kontekst = null;
        try {
            port.slettAvskrivning(_slettAvskrivning_systemID, _slettAvskrivning_journalnokkel, _slettAvskrivning_kontekst);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking slettKorrespondansepart...");
        no.geointegrasjon.arkiv.oppdatering.StringListe _slettKorrespondansepart_systemID = null;
        no.geointegrasjon.arkiv.oppdatering.Journpostnoekkel _slettKorrespondansepart_journalpostnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _slettKorrespondansepart_kontekst = null;
        try {
            port.slettKorrespondansepart(_slettKorrespondansepart_systemID, _slettKorrespondansepart_journalpostnokkel, _slettKorrespondansepart_kontekst);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking slettJournalpostMerknad...");
        no.geointegrasjon.arkiv.oppdatering.StringListe _slettJournalpostMerknad_systemID = null;
        no.geointegrasjon.arkiv.oppdatering.Journpostnoekkel _slettJournalpostMerknad_journalnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _slettJournalpostMerknad_kontekst = null;
        try {
            port.slettJournalpostMerknad(_slettJournalpostMerknad_systemID, _slettJournalpostMerknad_journalnokkel, _slettJournalpostMerknad_kontekst);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking nyBygning...");
        no.geointegrasjon.arkiv.oppdatering.ByggIdentListe _nyBygning_bygninger = null;
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel _nyBygning_saksnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _nyBygning_kontekst = null;
        try {
            port.nyBygning(_nyBygning_bygninger, _nyBygning_saksnokkel, _nyBygning_kontekst);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking nyDokument...");
        no.geointegrasjon.arkiv.oppdatering.Dokument _nyDokument_dokument = null;
        java.lang.Boolean _nyDokument_returnerFil = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _nyDokument_kontekst = null;
        try {
            no.geointegrasjon.arkiv.oppdatering.Dokument _nyDokument__return = port.nyDokument(_nyDokument_dokument, _nyDokument_returnerFil, _nyDokument_kontekst);
            System.out.println("nyDokument.result=" + _nyDokument__return);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking nyJournalpostTilleggsinformasjon...");
        no.geointegrasjon.arkiv.oppdatering.TilleggsinformasjonListe _nyJournalpostTilleggsinformasjon_tilleggsinfo = null;
        no.geointegrasjon.arkiv.oppdatering.Journpostnoekkel _nyJournalpostTilleggsinformasjon_journalnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _nyJournalpostTilleggsinformasjon_kontekst = null;
        try {
            port.nyJournalpostTilleggsinformasjon(_nyJournalpostTilleggsinformasjon_tilleggsinfo, _nyJournalpostTilleggsinformasjon_journalnokkel, _nyJournalpostTilleggsinformasjon_kontekst);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking oppdaterJournalpostAnsvarlig...");
        java.lang.String _oppdaterJournalpostAnsvarlig_nyAdministrativEnhetKode = "";
        java.lang.String _oppdaterJournalpostAnsvarlig_nySaksbehandlerInit = "";
        no.geointegrasjon.arkiv.oppdatering.Journpostnoekkel _oppdaterJournalpostAnsvarlig_journalpostnokkel = null;
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst _oppdaterJournalpostAnsvarlig_kontekst = null;
        try {
            no.geointegrasjon.arkiv.oppdatering.Journalpost _oppdaterJournalpostAnsvarlig__return = port.oppdaterJournalpostAnsvarlig(_oppdaterJournalpostAnsvarlig_nyAdministrativEnhetKode, _oppdaterJournalpostAnsvarlig_nySaksbehandlerInit, _oppdaterJournalpostAnsvarlig_journalpostnokkel, _oppdaterJournalpostAnsvarlig_kontekst);
            System.out.println("oppdaterJournalpostAnsvarlig.result=" + _oppdaterJournalpostAnsvarlig__return);

        } catch (ValidationException e) {
            System.out.println("Expected exception: ValidationException has occurred.");
            System.out.println(e.toString());
        } catch (FinderException e) {
            System.out.println("Expected exception: FinderException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException e) {
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        } catch (ImplementationException e) {
            System.out.println("Expected exception: ImplementationException has occurred.");
            System.out.println(e.toString());
        } catch (OperationalException e) {
            System.out.println("Expected exception: OperationalException has occurred.");
            System.out.println(e.toString());
        } catch (ApplicationException e) {
            System.out.println("Expected exception: ApplicationException has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
