package no.geointegrasjon.arkiv.oppdatering;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2024-12-18T13:51:15.069+01:00
 * Generated source version: 3.5.5
 *
 */
@WebService(targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", name = "SakArkivOppdateringPort")
@XmlSeeAlso({ObjectFactory.class})
public interface SakArkivOppdateringPort {

    @WebMethod(operationName = "FinnJournalpostRestanser", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#FinnJournalpostRestanser")
    @RequestWrapper(localName = "FinnJournalpostRestanser", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.FinnJournalpostRestanser")
    @ResponseWrapper(localName = "FinnJournalpostRestanserResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.FinnJournalpostRestanserResponse")
    @WebResult(name = "return", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
    public no.geointegrasjon.arkiv.oppdatering.JournalpostListe finnJournalpostRestanser(

        @WebParam(name = "ansvarlig", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Ansvarlig ansvarlig,
        @WebParam(name = "returnerMerknad", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerMerknad,
        @WebParam(name = "returnerTilleggsinformasjon", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerTilleggsinformasjon,
        @WebParam(name = "returnerKorrespondansepart", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerKorrespondansepart,
        @WebParam(name = "returnerAvskrivning", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerAvskrivning,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "OppdaterMappeStatus", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#OppdaterMappeStatus")
    @RequestWrapper(localName = "OppdaterMappeStatus", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.OppdaterMappeStatus")
    @ResponseWrapper(localName = "OppdaterMappeStatusResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.OppdaterMappeStatusResponse")
    @WebResult(name = "return", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
    public no.geointegrasjon.arkiv.oppdatering.Saksmappe oppdaterMappeStatus(

        @WebParam(name = "saksstatuskode", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Saksstatus saksstatuskode,
        @WebParam(name = "saksnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel saksnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "SlettBygning", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#SlettBygning")
    @RequestWrapper(localName = "SlettBygning", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.SlettBygning")
    @ResponseWrapper(localName = "SlettBygningResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.SlettBygningResponse")
    public void slettBygning(

        @WebParam(name = "bygninger", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ByggIdentListe bygninger,
        @WebParam(name = "saksnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel saksnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "NyAvskrivning", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#NyAvskrivning")
    @RequestWrapper(localName = "NyAvskrivning", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NyAvskrivning")
    @ResponseWrapper(localName = "NyAvskrivningResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NyAvskrivningResponse")
    public void nyAvskrivning(

        @WebParam(name = "avskrivning", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.AvskrivningListe avskrivning,
        @WebParam(name = "journalnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Journpostnoekkel journalnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "OppdaterPlan", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#OppdaterPlan")
    @RequestWrapper(localName = "OppdaterPlan", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.OppdaterPlan")
    @ResponseWrapper(localName = "OppdaterPlanResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.OppdaterPlanResponse")
    public void oppdaterPlan(

        @WebParam(name = "planid", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.NasjonalArealplanId planid,
        @WebParam(name = "saksnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel saksnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "NyPunkt", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#NyPunkt")
    @RequestWrapper(localName = "NyPunkt", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NyPunkt")
    @ResponseWrapper(localName = "NyPunktResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NyPunktResponse")
    public void nyPunkt(

        @WebParam(name = "posisjon", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.PunktListe posisjon,
        @WebParam(name = "saksnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel saksnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "NyJournalpostMerknad", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#NyJournalpostMerknad")
    @RequestWrapper(localName = "NyJournalpostMerknad", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NyJournalpostMerknad")
    @ResponseWrapper(localName = "NyJournalpostMerknadResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NyJournalpostMerknadResponse")
    public void nyJournalpostMerknad(

        @WebParam(name = "merknad", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.MerknadListe merknad,
        @WebParam(name = "journalnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Journpostnoekkel journalnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "SlettJournalpostTilleggsinformasjon", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#SlettJournalpostTilleggsinformasjon")
    @RequestWrapper(localName = "SlettJournalpostTilleggsinformasjon", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.SlettJournalpostTilleggsinformasjon")
    @ResponseWrapper(localName = "SlettJournalpostTilleggsinformasjonResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.SlettJournalpostTilleggsinformasjonResponse")
    public void slettJournalpostTilleggsinformasjon(

        @WebParam(name = "systemID", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.StringListe systemID,
        @WebParam(name = "journalnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Journpostnoekkel journalnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "NySaksmappe", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#NySaksmappe")
    @RequestWrapper(localName = "NySaksmappe", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NySaksmappe")
    @ResponseWrapper(localName = "NySaksmappeResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NySaksmappeResponse")
    @WebResult(name = "return", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
    public no.geointegrasjon.arkiv.oppdatering.Saksmappe nySaksmappe(

        @WebParam(name = "mappe", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Saksmappe mappe,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "OppdaterJournalpostEksternNoekkel", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#OppdaterJournalpostEksternNoekkel")
    @RequestWrapper(localName = "OppdaterJournalpostEksternNoekkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.OppdaterJournalpostEksternNoekkel")
    @ResponseWrapper(localName = "OppdaterJournalpostEksternNoekkelResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.OppdaterJournalpostEksternNoekkelResponse")
    @WebResult(name = "return", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
    public no.geointegrasjon.arkiv.oppdatering.Journalpost oppdaterJournalpostEksternNoekkel(

        @WebParam(name = "nokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.EksternNoekkel nokkel,
        @WebParam(name = "journalpostnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Journpostnoekkel journalpostnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "SlettMatrikkelnummer", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#SlettMatrikkelnummer")
    @RequestWrapper(localName = "SlettMatrikkelnummer", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.SlettMatrikkelnummer")
    @ResponseWrapper(localName = "SlettMatrikkelnummerResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.SlettMatrikkelnummerResponse")
    public void slettMatrikkelnummer(

        @WebParam(name = "matrikkelnr", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.MatrikkelnummerListe matrikkelnr,
        @WebParam(name = "saksnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel saksnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "NySaksmappeTilleggsinformasjon", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#NySaksmappeTilleggsinformasjon")
    @RequestWrapper(localName = "NySaksmappeTilleggsinformasjon", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NySaksmappeTilleggsinformasjon")
    @ResponseWrapper(localName = "NySaksmappeTilleggsinformasjonResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NySaksmappeTilleggsinformasjonResponse")
    public void nySaksmappeTilleggsinformasjon(

        @WebParam(name = "tilleggsinfo", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.TilleggsinformasjonListe tilleggsinfo,
        @WebParam(name = "saksnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel saksnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "OppdaterJournalpostStatus", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#OppdaterJournalpostStatus")
    @RequestWrapper(localName = "OppdaterJournalpostStatus", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.OppdaterJournalpostStatus")
    @ResponseWrapper(localName = "OppdaterJournalpostStatusResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.OppdaterJournalpostStatusResponse")
    public void oppdaterJournalpostStatus(

        @WebParam(name = "journalstatus", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Journalstatus journalstatus,
        @WebParam(name = "journalpostnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Journpostnoekkel journalpostnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "NySakspart", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#NySakspart")
    @RequestWrapper(localName = "NySakspart", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NySakspart")
    @ResponseWrapper(localName = "NySakspartResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NySakspartResponse")
    public void nySakspart(

        @WebParam(name = "sakspart", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.SakspartListe sakspart,
        @WebParam(name = "saksnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel saksnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "FinnJournalposterUnderArbeid", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#FinnJournalposterUnderArbeid")
    @RequestWrapper(localName = "FinnJournalposterUnderArbeid", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.FinnJournalposterUnderArbeid")
    @ResponseWrapper(localName = "FinnJournalposterUnderArbeidResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.FinnJournalposterUnderArbeidResponse")
    @WebResult(name = "return", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
    public no.geointegrasjon.arkiv.oppdatering.JournalpostListe finnJournalposterUnderArbeid(

        @WebParam(name = "ansvarlig", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Ansvarlig ansvarlig,
        @WebParam(name = "returnerMerknad", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerMerknad,
        @WebParam(name = "returnerTilleggsinformasjon", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerTilleggsinformasjon,
        @WebParam(name = "returnerKorrespondansepart", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerKorrespondansepart,
        @WebParam(name = "returnerAvskrivning", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerAvskrivning,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "NyMatrikkelnummer", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#NyMatrikkelnummer")
    @RequestWrapper(localName = "NyMatrikkelnummer", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NyMatrikkelnummer")
    @ResponseWrapper(localName = "NyMatrikkelnummerResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NyMatrikkelnummerResponse")
    public void nyMatrikkelnummer(

        @WebParam(name = "matrikkelnr", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.MatrikkelnummerListe matrikkelnr,
        @WebParam(name = "saksnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel saksnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "NyKorrespondansepart", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#NyKorrespondansepart")
    @RequestWrapper(localName = "NyKorrespondansepart", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NyKorrespondansepart")
    @ResponseWrapper(localName = "NyKorrespondansepartResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NyKorrespondansepartResponse")
    public void nyKorrespondansepart(

        @WebParam(name = "part", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.KorrespondansepartListe part,
        @WebParam(name = "journalpostnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Journpostnoekkel journalpostnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "SlettPunkt", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#SlettPunkt")
    @RequestWrapper(localName = "SlettPunkt", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.SlettPunkt")
    @ResponseWrapper(localName = "SlettPunktResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.SlettPunktResponse")
    public void slettPunkt(

        @WebParam(name = "posisjon", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.PunktListe posisjon,
        @WebParam(name = "saksnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel saksnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "NyJournalpost", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#NyJournalpost")
    @RequestWrapper(localName = "NyJournalpost", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NyJournalpost")
    @ResponseWrapper(localName = "NyJournalpostResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NyJournalpostResponse")
    @WebResult(name = "return", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
    public no.geointegrasjon.arkiv.oppdatering.Journalpost nyJournalpost(

        @WebParam(name = "journalpost", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Journalpost journalpost,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "OppdaterMappeEksternNoekkel", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#OppdaterMappeEksternNoekkel")
    @RequestWrapper(localName = "OppdaterMappeEksternNoekkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.OppdaterMappeEksternNoekkel")
    @ResponseWrapper(localName = "OppdaterMappeEksternNoekkelResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.OppdaterMappeEksternNoekkelResponse")
    @WebResult(name = "return", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
    public no.geointegrasjon.arkiv.oppdatering.Saksmappe oppdaterMappeEksternNoekkel(

        @WebParam(name = "nokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.EksternNoekkel nokkel,
        @WebParam(name = "saksnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel saksnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "NySaksmappeMerknad", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#NySaksmappeMerknad")
    @RequestWrapper(localName = "NySaksmappeMerknad", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NySaksmappeMerknad")
    @ResponseWrapper(localName = "NySaksmappeMerknadResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NySaksmappeMerknadResponse")
    public void nySaksmappeMerknad(

        @WebParam(name = "merknad", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.MerknadListe merknad,
        @WebParam(name = "saksnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel saksnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "OppdaterMappeAnsvarlig", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#OppdaterMappeAnsvarlig")
    @RequestWrapper(localName = "OppdaterMappeAnsvarlig", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.OppdaterMappeAnsvarlig")
    @ResponseWrapper(localName = "OppdaterMappeAnsvarligResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.OppdaterMappeAnsvarligResponse")
    @WebResult(name = "return", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
    public no.geointegrasjon.arkiv.oppdatering.Saksmappe oppdaterMappeAnsvarlig(

        @WebParam(name = "nyAdministrativEnhetKode", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        java.lang.String nyAdministrativEnhetKode,
        @WebParam(name = "nySaksbehandlerInit", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        java.lang.String nySaksbehandlerInit,
        @WebParam(name = "saksnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel saksnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "SlettSaksmappeTilleggsinformasjon", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#SlettSaksmappeTilleggsinformasjon")
    @RequestWrapper(localName = "SlettSaksmappeTilleggsinformasjon", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.SlettSaksmappeTilleggsinformasjon")
    @ResponseWrapper(localName = "SlettSaksmappeTilleggsinformasjonResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.SlettSaksmappeTilleggsinformasjonResponse")
    public void slettSaksmappeTilleggsinformasjon(

        @WebParam(name = "systemID", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.StringListe systemID,
        @WebParam(name = "saksnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel saksnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "SlettSakspart", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#SlettSakspart")
    @RequestWrapper(localName = "SlettSakspart", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.SlettSakspart")
    @ResponseWrapper(localName = "SlettSakspartResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.SlettSakspartResponse")
    public void slettSakspart(

        @WebParam(name = "systemID", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.StringListe systemID,
        @WebParam(name = "saksnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel saksnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "SlettSaksmappeMerknad", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#SlettSaksmappeMerknad")
    @RequestWrapper(localName = "SlettSaksmappeMerknad", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.SlettSaksmappeMerknad")
    @ResponseWrapper(localName = "SlettSaksmappeMerknadResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.SlettSaksmappeMerknadResponse")
    public void slettSaksmappeMerknad(

        @WebParam(name = "systemID", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.StringListe systemID,
        @WebParam(name = "saksnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel saksnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "SlettAvskrivning", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#SlettAvskrivning")
    @RequestWrapper(localName = "SlettAvskrivning", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.SlettAvskrivning")
    @ResponseWrapper(localName = "SlettAvskrivningResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.SlettAvskrivningResponse")
    public void slettAvskrivning(

        @WebParam(name = "systemID", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.StringListe systemID,
        @WebParam(name = "journalnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Journpostnoekkel journalnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "SlettKorrespondansepart", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#SlettKorrespondansepart")
    @RequestWrapper(localName = "SlettKorrespondansepart", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.SlettKorrespondansepart")
    @ResponseWrapper(localName = "SlettKorrespondansepartResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.SlettKorrespondansepartResponse")
    public void slettKorrespondansepart(

        @WebParam(name = "systemID", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.StringListe systemID,
        @WebParam(name = "journalpostnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Journpostnoekkel journalpostnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "SlettJournalpostMerknad", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#SlettJournalpostMerknad")
    @RequestWrapper(localName = "SlettJournalpostMerknad", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.SlettJournalpostMerknad")
    @ResponseWrapper(localName = "SlettJournalpostMerknadResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.SlettJournalpostMerknadResponse")
    public void slettJournalpostMerknad(

        @WebParam(name = "systemID", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.StringListe systemID,
        @WebParam(name = "journalnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Journpostnoekkel journalnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "NyBygning", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#NyBygning")
    @RequestWrapper(localName = "NyBygning", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NyBygning")
    @ResponseWrapper(localName = "NyBygningResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NyBygningResponse")
    public void nyBygning(

        @WebParam(name = "bygninger", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ByggIdentListe bygninger,
        @WebParam(name = "saksnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Saksnoekkel saksnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "NyDokument", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#NyDokument")
    @RequestWrapper(localName = "NyDokument", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NyDokument")
    @ResponseWrapper(localName = "NyDokumentResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NyDokumentResponse")
    @WebResult(name = "return", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
    public no.geointegrasjon.arkiv.oppdatering.Dokument nyDokument(

        @WebParam(name = "dokument", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Dokument dokument,
        @WebParam(name = "returnerFil", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerFil,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "NyJournalpostTilleggsinformasjon", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#NyJournalpostTilleggsinformasjon")
    @RequestWrapper(localName = "NyJournalpostTilleggsinformasjon", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NyJournalpostTilleggsinformasjon")
    @ResponseWrapper(localName = "NyJournalpostTilleggsinformasjonResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.NyJournalpostTilleggsinformasjonResponse")
    public void nyJournalpostTilleggsinformasjon(

        @WebParam(name = "tilleggsinfo", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.TilleggsinformasjonListe tilleggsinfo,
        @WebParam(name = "journalnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Journpostnoekkel journalnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "OppdaterJournalpostAnsvarlig", action = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31/#OppdaterJournalpostAnsvarlig")
    @RequestWrapper(localName = "OppdaterJournalpostAnsvarlig", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.OppdaterJournalpostAnsvarlig")
    @ResponseWrapper(localName = "OppdaterJournalpostAnsvarligResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.oppdatering.OppdaterJournalpostAnsvarligResponse")
    @WebResult(name = "return", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
    public no.geointegrasjon.arkiv.oppdatering.Journalpost oppdaterJournalpostAnsvarlig(

        @WebParam(name = "nyAdministrativEnhetKode", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        java.lang.String nyAdministrativEnhetKode,
        @WebParam(name = "nySaksbehandlerInit", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        java.lang.String nySaksbehandlerInit,
        @WebParam(name = "journalpostnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.Journpostnoekkel journalpostnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Oppdatering/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.oppdatering.ArkivKontekst kontekst
    ) throws ValidationException, FinderException, SystemException, ImplementationException, OperationalException, ApplicationException;
}
