
package no.geointegrasjon.arkiv.innsyn;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.5
 * 2024-12-18T13:51:13.631+01:00
 * Generated source version: 3.5.5
 */

@WebFault(name = "ApplicationFault", targetNamespace = "http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")
public class ApplicationException extends Exception {

    private no.geointegrasjon.arkiv.innsyn.ApplicationFault faultInfo;

    public ApplicationException() {
        super();
    }

    public ApplicationException(String message) {
        super(message);
    }

    public ApplicationException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ApplicationException(String message, no.geointegrasjon.arkiv.innsyn.ApplicationFault applicationFault) {
        super(message);
        this.faultInfo = applicationFault;
    }

    public ApplicationException(String message, no.geointegrasjon.arkiv.innsyn.ApplicationFault applicationFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = applicationFault;
    }

    public no.geointegrasjon.arkiv.innsyn.ApplicationFault getFaultInfo() {
        return this.faultInfo;
    }
}
