package no.geointegrasjon.arkiv.innsyn;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2024-12-18T13:51:13.635+01:00
 * Generated source version: 3.5.5
 *
 */
@WebService(targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", name = "ArkivInnsynPort")
@XmlSeeAlso({ObjectFactory.class})
public interface ArkivInnsynPort {

    @WebMethod(operationName = "FinnDokumenter", action = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31/#FinnDokumenter")
    @RequestWrapper(localName = "FinnDokumenter", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.innsyn.FinnDokumenter")
    @ResponseWrapper(localName = "FinnDokumenterResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.innsyn.FinnDokumenterResponse")
    @WebResult(name = "return", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
    public no.geointegrasjon.arkiv.innsyn.DokumentListe finnDokumenter(

        @WebParam(name = "sok", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.innsyn.SoekskriterieListe sok,
        @WebParam(name = "returnerFil", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerFil,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.innsyn.ArkivKontekst kontekst
    ) throws SystemException, ImplementationException, FinderException, ValidationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "FinnJournalposter", action = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31/#FinnJournalposter")
    @RequestWrapper(localName = "FinnJournalposter", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.innsyn.FinnJournalposter")
    @ResponseWrapper(localName = "FinnJournalposterResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.innsyn.FinnJournalposterResponse")
    @WebResult(name = "return", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
    public no.geointegrasjon.arkiv.innsyn.JournalpostListe finnJournalposter(

        @WebParam(name = "sok", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.innsyn.SoekskriterieListe sok,
        @WebParam(name = "returnerMerknad", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerMerknad,
        @WebParam(name = "returnerTilleggsinformasjon", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerTilleggsinformasjon,
        @WebParam(name = "returnerKorrespondansepart", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerKorrespondansepart,
        @WebParam(name = "returnerAvskrivning", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerAvskrivning,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.innsyn.ArkivKontekst kontekst
    ) throws SystemException, ImplementationException, FinderException, ValidationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "FinnSaksmapperGittNoekkel", action = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31/#FinnSaksmapperGittNoekkel")
    @RequestWrapper(localName = "FinnSaksmapperGittNoekkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.innsyn.FinnSaksmapperGittNoekkel")
    @ResponseWrapper(localName = "FinnSaksmapperGittNoekkelResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.innsyn.FinnSaksmapperGittNoekkelResponse")
    @WebResult(name = "return", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
    public no.geointegrasjon.arkiv.innsyn.SaksmappeListe finnSaksmapperGittNoekkel(

        @WebParam(name = "nokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.innsyn.Saksnoekkel nokkel,
        @WebParam(name = "returnerMerknad", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerMerknad,
        @WebParam(name = "returnerTilleggsinformasjon", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerTilleggsinformasjon,
        @WebParam(name = "returnerSakspart", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerSakspart,
        @WebParam(name = "returnerKlasse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerKlasse,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.innsyn.ArkivKontekst kontekst
    ) throws SystemException, ImplementationException, FinderException, ValidationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "FinnJournalposterGittSaksmappeNoekkel", action = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31/#FinnJournalposterGittSaksmappeNoekkel")
    @RequestWrapper(localName = "FinnJournalposterGittSaksmappeNoekkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.innsyn.FinnJournalposterGittSaksmappeNoekkel")
    @ResponseWrapper(localName = "FinnJournalposterGittSaksmappeNoekkelResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.innsyn.FinnJournalposterGittSaksmappeNoekkelResponse")
    @WebResult(name = "return", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
    public no.geointegrasjon.arkiv.innsyn.JournalpostListe finnJournalposterGittSaksmappeNoekkel(

        @WebParam(name = "nokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.innsyn.Saksnoekkel nokkel,
        @WebParam(name = "returnerMerknad", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerMerknad,
        @WebParam(name = "returnerTilleggsinformasjon", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerTilleggsinformasjon,
        @WebParam(name = "returnerKorrespondansepart", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerKorrespondansepart,
        @WebParam(name = "returnerAvskrivning", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerAvskrivning,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.innsyn.ArkivKontekst kontekst
    ) throws SystemException, ImplementationException, FinderException, ValidationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "FinnJournalposterGittNoekkel", action = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31/#FinnJournalposterGittNoekkel")
    @RequestWrapper(localName = "FinnJournalposterGittNoekkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.innsyn.FinnJournalposterGittNoekkel")
    @ResponseWrapper(localName = "FinnJournalposterGittNoekkelResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.innsyn.FinnJournalposterGittNoekkelResponse")
    @WebResult(name = "return", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
    public no.geointegrasjon.arkiv.innsyn.JournalpostListe finnJournalposterGittNoekkel(

        @WebParam(name = "nokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.innsyn.Journpostnoekkel nokkel,
        @WebParam(name = "returnerMerknad", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerMerknad,
        @WebParam(name = "returnerTilleggsinformasjon", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerTilleggsinformasjon,
        @WebParam(name = "returnerKorrespondansepart", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerKorrespondansepart,
        @WebParam(name = "returnerAvskrivning", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerAvskrivning,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.innsyn.ArkivKontekst kontekst
    ) throws SystemException, ImplementationException, FinderException, ValidationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "FinnDokumenterGittSaksnoekkel", action = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31/#FinnDokumenterGittSaksnoekkel")
    @RequestWrapper(localName = "FinnDokumenterGittSaksnoekkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.innsyn.FinnDokumenterGittSaksnoekkel")
    @ResponseWrapper(localName = "FinnDokumenterGittSaksnoekkelResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.innsyn.FinnDokumenterGittSaksnoekkelResponse")
    @WebResult(name = "return", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
    public no.geointegrasjon.arkiv.innsyn.DokumentListe finnDokumenterGittSaksnoekkel(

        @WebParam(name = "saksnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.innsyn.Saksnoekkel saksnokkel,
        @WebParam(name = "returnerFil", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerFil,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.innsyn.ArkivKontekst kontekst
    ) throws SystemException, ImplementationException, FinderException, ValidationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "FinnDokumenterGittJournalpostnoekkel", action = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31/#FinnDokumenterGittJournalpostnoekkel")
    @RequestWrapper(localName = "FinnDokumenterGittJournalpostnoekkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.innsyn.FinnDokumenterGittJournalpostnoekkel")
    @ResponseWrapper(localName = "FinnDokumenterGittJournalpostnoekkelResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.innsyn.FinnDokumenterGittJournalpostnoekkelResponse")
    @WebResult(name = "return", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
    public no.geointegrasjon.arkiv.innsyn.DokumentListe finnDokumenterGittJournalpostnoekkel(

        @WebParam(name = "journpostnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.innsyn.Journpostnoekkel journpostnokkel,
        @WebParam(name = "returnerFil", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerFil,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.innsyn.ArkivKontekst kontekst
    ) throws SystemException, ImplementationException, FinderException, ValidationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "FinnSaksmapper", action = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31/#FinnSaksmapper")
    @RequestWrapper(localName = "FinnSaksmapper", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.innsyn.FinnSaksmapper")
    @ResponseWrapper(localName = "FinnSaksmapperResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.innsyn.FinnSaksmapperResponse")
    @WebResult(name = "return", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
    public no.geointegrasjon.arkiv.innsyn.SaksmappeListe finnSaksmapper(

        @WebParam(name = "sok", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.innsyn.SoekskriterieListe sok,
        @WebParam(name = "returnerMerknad", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerMerknad,
        @WebParam(name = "returnerTilleggsinformasjon", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerTilleggsinformasjon,
        @WebParam(name = "returnerSakspart", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerSakspart,
        @WebParam(name = "returnerKlasse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.Boolean returnerKlasse,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.innsyn.ArkivKontekst kontekst
    ) throws SystemException, ImplementationException, FinderException, ValidationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "FinnDokumenttyper", action = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31/#FinnDokumenttyper")
    @RequestWrapper(localName = "FinnDokumenttyper", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.innsyn.FinnDokumenttyper")
    @ResponseWrapper(localName = "FinnDokumenttyperResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.innsyn.FinnDokumenttyperResponse")
    @WebResult(name = "return", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
    public no.geointegrasjon.arkiv.innsyn.DokumenttypeListe finnDokumenttyper(

        @WebParam(name = "saksnokkel", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.innsyn.Saksnoekkel saksnokkel,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.innsyn.ArkivKontekst kontekst
    ) throws SystemException, ImplementationException, FinderException, ValidationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "HentKodeliste", action = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31/#HentKodeliste")
    @RequestWrapper(localName = "HentKodeliste", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.innsyn.HentKodeliste")
    @ResponseWrapper(localName = "HentKodelisteResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.innsyn.HentKodelisteResponse")
    @WebResult(name = "return", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
    public no.geointegrasjon.arkiv.innsyn.KodeListe hentKodeliste(

        @WebParam(name = "kodelistenavn", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        java.lang.String kodelistenavn,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.innsyn.ArkivKontekst kontekst
    ) throws SystemException, ImplementationException, FinderException, ValidationException, OperationalException, ApplicationException;

    @WebMethod(operationName = "HentFil", action = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31/#HentFil")
    @RequestWrapper(localName = "HentFil", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.innsyn.HentFil")
    @ResponseWrapper(localName = "HentFilResponse", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31", className = "no.geointegrasjon.arkiv.innsyn.HentFilResponse")
    @WebResult(name = "return", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
    public no.geointegrasjon.arkiv.innsyn.Fil hentFil(

        @WebParam(name = "systemid", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.innsyn.SystemID systemid,
        @WebParam(name = "kontekst", targetNamespace = "http://rep.geointegrasjon.no/Arkiv/Innsyn/xml.wsdl/2012.01.31")
        no.geointegrasjon.arkiv.innsyn.ArkivKontekst kontekst
    ) throws SystemException, ImplementationException, FinderException, ValidationException, OperationalException, ApplicationException;
}
