apiVersion: apps/v1
kind: Deployment
metadata:
  name: adapter-arkiv-acos
spec:
  template:
    spec:
      containers:
        - name: adapter-arkiv-acos
          image: fintlabsacr.azurecr.io/fint-geointegrasjon-adapter:disp-8.1-7849323
          envFrom:
            - secretRef:
                name: arkiv-samediggi-acos
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Xmx1G -verbose:gc
                -XX:+ExitOnOutOfMemoryError
                -Dfile.encoding=UTF-8
            - {name: springfox.title, value: "Samediggi ACOS GeoIntegrasjon"}
            - {name: fint.adapter.organizations, value: samediggi.no}
            - {name: fint.adapter.reject-unknown-events, value: 'false'}
            - {name: fint.case.defaults.tilskuddfartoy.title.cases, value: 'Tilskudd - fartøyvern - ${kallesignal} ${fartoyNavn}'}
            - {name: fint.case.defaults.tilskuddfartoy.field.fartoy, value: '${kallesignal} ${fartoyNavn}' }
            - {name: fint.case.defaults.tilskuddfartoy.field.soknadsnummer, value: '${soknadsnummer.identifikatorverdi}' }
            - {name: fint.case.defaults.tilskuddfartoy.field.kulturminneid, value: '${kulturminneId}' }
            - {name: fint.case.defaults.tilskuddfartoy.arkivdel, value: SA }
            - {name: fint.case.defaults.tilskuddfartoy.journalpostType, value: I }
            - {name: fint.case.defaults.tilskuddfartoy.saksstatus, value: B }
            - {name: fint.case.defaults.tilskuddfartoy.journalstatus, value: J }
            - {name: fint.case.defaults.tilskuddfartoy.dokumentstatus, value: F }
            - {name: fint.case.defaults.tilskuddfartoy.administrativEnhet, value: SUPREKM }
            - {name: fint.case.defaults.tilskuddfartoy.journalenhet, value: PM }
            - {name: fint.case.defaults.tilskuddfartoy.saksansvarlig, value: GREVOR }
            - {name: fint.case.defaults.tilskuddfartoy.saksbehandler, value: GREVOR }
            - {name: fint.case.defaults.tilskuddfartoy.klassifikasjon.1.ordning, value: 'FE'}
            - {name: fint.case.defaults.tilskuddfartoy.klassifikasjon.1.verdi, value: '243'}
            - {name: fint.case.defaults.tilskuddfartoy.klassifikasjon.2.ordning, value: 'FA'}
            - {name: fint.case.defaults.tilskuddfartoy.klassifikasjon.2.verdi, value: 'C54'}
            - {name: fint.case.defaults.tilskuddfredabygningprivateie.title.cases, value: 'Tilskudd - fredete bygninger i privat eie - gnr ${matrikkelnummer.gardsnummer} bnr ${matrikkelnummer.bruksnummer} - ${bygningsnavn}'}
            - {name: fint.case.defaults.tilskuddfredabygningprivateie.field.matrikkel, value: '${matrikkelnummer.gardsnummer}/${matrikkelnummer.bruksnummer}' }
            - {name: fint.case.defaults.tilskuddfredabygningprivateie.field.soknadsnummer, value: '${soknadsnummer.identifikatorverdi}' }
            - {name: fint.case.defaults.tilskuddfredabygningprivateie.field.kulturminneid, value: '${kulturminneId}' }
            - {name: fint.case.defaults.tilskuddfredabygningprivateie.arkivdel, value: SA }
            - {name: fint.case.defaults.tilskuddfredabygningprivateie.journalpostType, value: I }
            - {name: fint.case.defaults.tilskuddfredabygningprivateie.saksstatus, value: B }
            - {name: fint.case.defaults.tilskuddfredabygningprivateie.journalstatus, value: J }
            - {name: fint.case.defaults.tilskuddfredabygningprivateie.dokumentstatus, value: F }
            - {name: fint.case.defaults.tilskuddfredabygningprivateie.administrativEnhet, value: SUPREKM }
            - {name: fint.case.defaults.tilskuddfredabygningprivateie.journalenhet, value: PM }
            - {name: fint.case.defaults.tilskuddfredabygningprivateie.saksansvarlig, value: GREVOR }
            - {name: fint.case.defaults.tilskuddfredabygningprivateie.saksbehandler, value: GREVOR }
            - {name: fint.case.defaults.tilskuddfredabygningprivateie.klassifikasjon.1.ordning, value: 'FE'}
            - {name: fint.case.defaults.tilskuddfredabygningprivateie.klassifikasjon.1.verdi, value: '243'}
            - {name: fint.case.defaults.tilskuddfredabygningprivateie.klassifikasjon.2.ordning, value: 'FA'}
            - {name: fint.case.defaults.tilskuddfredabygningprivateie.klassifikasjon.2.verdi, value: 'C53'}
            - {name: fint.case.coding.korrespondanseparttype.EA, value: A}
            - {name: fint.case.coding.korrespondanseparttype.EM, value: M}
            - {name: fint.internal-files.type, value: 'BLOB'}
            - {name: fint.internal-files.connection-string, valueFrom: {secretKeyRef: {name: adapter-storage, key: connection-string}}}
            - {name: fint.adapter.endpoints.providers.kodeverk, value: https://beta.felleskomponent.no/arkiv/kodeverk/provider}
            - {name: fint.adapter.endpoints.providers.noark, value: https://beta.felleskomponent.no/arkiv/noark/provider}
            - {name: fint.adapter.endpoints.providers.kulturminne, value: https://beta.felleskomponent.no/arkiv/kulturminnevern/provider}
            - {name: fint.geointegrasjon.tracing, value: 'true' }
            - {name: fint.geointegrasjon.use-wss, value: 'true' }
            - {name: fint.geointegrasjon.fagsystem, value: 'DIGISAK'}
            - {name: fint.geointegrasjon.tilleggstype, value: 'TILLEGG'}
