apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mrfylke-no

resources:
  - ../../../base
  - onepassword.yaml
  - fint-adapter.yaml

commonLabels:
  app.kubernetes.io/instance: adapter-arkiv-acos_mrfylke-no
  fintlabs.no/org-id: mrfylke-no

patches:

  - target:
      kind: Deployment
      name: adapter-arkiv-acos
    path: deployment.yaml
