apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nfk-no

resources:
  - ../../../base
  - onepassword.yaml

commonLabels:
  app.kubernetes.io/instance: adapter-arkiv-acos_nfk-no
  fintlabs.no/org-id: nfk.no

patches:
  
  - target:
      kind: Deployment
      name: adapter-arkiv-acos
    path: deployment.yaml
