apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: bym-oslo-kommune-no

resources:
  - ../../../base
  - onepassword.yaml

commonLabels:
  fintlabs.no/org-id: oslo-kommune-no

patches:
  
  - target:
      kind: Deployment
      name: adapter-arkiv-acos
    path: deployment.yaml

  - target:
      kind: Deployment
      name: adapter-arkiv-acos
    patch: |-
      - op: replace
        path: "/metadata/name"
        value: "adapter-arkiv-bym-oslo-acos"
      - op: replace
        path: "/spec/selector/matchLabels/app"
        value: "adapter-arkiv-bym-oslo-acos"
      - op: replace
        path: "/spec/template/metadata/labels/app"
        value: "adapter-arkiv-bym-oslo-acos"
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: "adapter-arkiv-bym-oslo-acos"

