apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: bym-oslo-kommune-no

resources:
  - ../../../base
  - onepassword.yaml

#commonLabels:
#  app.kubernetes.io/instance: adapter-sikri-arkiv_fridiks-no
#  fintlabs.no/org-id: fridiks.no

patches:
  
  - target:
      kind: Deployment
      name: adapter-arkiv-bym-oslo-acos
    path: deployment.yaml
