apiVersion: apps/v1
kind: Deployment
metadata:
  name: adapter-arkiv-acos
spec:
  selector:
    matchLabels:
      app: adapter-arkiv-acos
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: adapter-arkiv-acos
        app.kubernetes.io/name: adapter-arkiv-acos
        app.kubernetes.io/component: adapter
        app.kubernetes.io/part-of: fint-arkiv
        fintlabs.no/team: arkiv
        observability.fintlabs.no/loki: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8091"
        prometheus.io/path: "prometheus"
    spec:
      restartPolicy: Always
      containers:
        - name: adapter-arkiv-acos
          image: ghcr.io/fintlabs/fint-geointegrasjon-adapter:latest
          resources:
            limits:
              memory: "6Gi"
              cpu: "2"
            requests:
              memory: "5Gi"
              cpu: "500m"
          ports:
            - containerPort: 8091
          readinessProbe:
            httpGet:
              path: /health
              port: 8091
            initialDelaySeconds: 10
            timeoutSeconds: 5
          env:
            - {name: TZ, value: Europe/Oslo}
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Xmx5G -verbose:gc
                -XX:+ExitOnOutOfMemoryError
                -Dfile.encoding=UTF-8
            - {name: security.basic.enabled, value: "false"}
            - {name: endpoints.enabled, value: "false"}
            - {name: endpoints.sensitive, value: "false"}
            - {name: endpoints.health.enabled, value: "true" }
            - {name: endpoints.prometheus.enabled, value: "true" }
            - {name: endpoints.metrics.enabled, value: "true" }
            - {name: fint.adapter.reject-unknown-events, value: 'false'}
            - {name: fint.case.coding.korrespondanseparttype.EA, value: A}
            - {name: fint.case.coding.korrespondanseparttype.EM, value: M}
            - {name: fint.case.coding.filformat.RA-JPEG, value: 'JPG'}
            - {name: fint.case.coding.filformat.RA-PDF, value: 'PDF'}
            - {name: fint.case.coding.filformat.RA-TEKST, value: 'TXT'}
            - {name: fint.case.coding.filformat.RA-TIFF6, value: 'TIF'}
            - {name: fint.internal-files.type, value: 'BLOB'}
            - {name: fint.geointegrasjon.tracing, value: 'true' }
            - {name: fint.geointegrasjon.use-wss, value: 'false' }
            - {name: fint.geointegrasjon.fagsystem, value: ''}
            - {name: fint.geointegrasjon.tilleggstype, value: ''}
