name: Build, Push and Deploy

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: read

jobs:

  build-push:
    uses: fintlabs/shared-workflows/.github/workflows/java-gradle-build-push.yaml@main
    with:
      java-version: '8'
    secrets: inherit

  beta:
    needs: build-push
    uses: fintlabs/shared-workflows/.github/workflows/java-kustomize-deploy.yaml@main
    strategy:
      matrix:
        org: [ bym-oslo-kommune-no ]
    with:
      tags: ${{ needs.build-push.outputs.tags }}
      environment: beta
      org: ${{ matrix.org }}
      deploy-every-branch: true
    secrets: inherit

  prod:
    needs: [ build-push, beta ]
    uses: fintlabs/shared-workflows/.github/workflows/java-kustomize-deploy.yaml@main
    strategy:
      matrix:
        org: [ nfk-no, mrfylke-no ]
    with:
      tags: ${{ needs.build-push.outputs.tags }}
      environment: api
      org: ${{ matrix.org }}
    secrets: inherit