---
name: CI

on:
  push:
    branches-ignore:
      - master

permissions:
  packages: read
  contents: read

jobs:

  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'corretto'
          cache: 'gradle'

      - uses: gradle/wrapper-validation-action@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Trigger CD
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUBACTION_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-cd